[project]
name = "desktop-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio==4.0.0",
    "azure-cosmos==4.16.3",
    "fastapi==0.136.1",
    "httpx==0.28.1",
    "pydantic==2.13.3",
    "pydantic-settings==2.14.2",
    "pywebview[gtk]==6.2.1",
    "uvicorn==0.46.0",
]
